import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";
import builtins from 'builtin-modules'

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const wasmSource = path.resolve('node_modules/jieba-wasm/pkg/web/jieba_rs_wasm_bg.wasm');
const wasmTarget = path.resolve('jieba_rs_wasm_bg.wasm');

const copyJiebaWasm = {
	name: 'copy-jieba-wasm',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			fs.copyFileSync(wasmSource, wasmTarget);
		});
	},
};

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['src/index.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/closebrackets',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/comment',
		'@codemirror/fold',
		'@codemirror/gutter',
		'@codemirror/highlight',
		'@codemirror/history',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/matchbrackets',
		'@codemirror/panel',
		'@codemirror/rangeset',
		'@codemirror/rectangular-selection',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/stream-parser',
		'@codemirror/text',
		'@codemirror/tooltip',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	platform: 'node',
	mainFields: ['browser', 'module', 'main'],
	watch: !prod,
	target: 'es2016',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	plugins: [copyJiebaWasm],
}).catch(() => process.exit(1));
